FROM node:19-slim

WORKDIR /home/node/app

RUN useradd --user-group --create-home --shell /bin/false app &&\
  npm install --global npm@9.6.5 && npm install -g prisma

RUN chmod -R 7777 /home/node/app

COPY package.json .

RUN npm install --silent

COPY . .

COPY .env.example .env

RUN prisma migrate dev

EXPOSE 3000

CMD [ "npm", "run", "dev" ]